version: 2
 
sources:
  - name: qwt_raw
    database: QWT_ANALYTICS_DEV
    schema: RAW_DEV
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_orders
      - name: raw_orderdetails
      - name: raw_employees
      - name: raw_empoffice