version: 2
 
sources:
  - name: qwt_raw
    database: "{{env_var('DBT_QWTDB', 'QWT_ANALYTICS_DEV')}}"
    schema: "{{env_var('DBT_RAWSCHEMA', 'RAW_DEV')}}"
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_orders
      - name: raw_orderdetails
      - name: raw_employees
      - name: raw_empoffice
      - name: raw_shipments
      - name: raw_suppliers