version: 2

seeds:
  - name: lkp_divisions
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"

  - name: lkp_catagory
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"
  - name: lkp_shippers
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"